config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'branches#index'
  resources :branches, only: [:new, :create, :edit, :update, :destroy] do
    resources :employees, only: :index
    resources :holidays, only: [:new, :create]
  end
  resources :holidays, only: [:index, :destroy]
  resources :employees, only: [:new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch.rb
class Branch < ApplicationRecord
  validates :name, presence: true

  belongs_to :user
  has_many :employees, dependent: :destroy
end

app/models/employee.rb
class Employee < ApplicationRecord
  validates :name, :employment_status, :hire_date, presence: true

  belongs_to :branch
  has_many :holidays, dependent: :destroy

  def grant_date
    hire_date >> 6
  end

  def year_of_service
    if Date.today.month - hire_date.month >= 0
      year = Date.today.year - hire_date.year
      month = Date.today.month - hire_date.month
    else
      year = Date.today.year - hire_date.year - 1
      month = Date.today.month - hire_date.month + 12
    end
    "#{year}年#{month}ヵ月"
  end

  def range_to_delete
    month = grant_date.month
    day = grant_date.mday
    year = Date.today.year
    last_grant_date = Time.local(year, month, day)

    if last_grant_date > Date.today
      last_year = year - 1
      last_grant_date = Time.local(last_year, month, day)
    end
    holidays.where(registration_date: last_grant_date..Date.tomorrow)
  end

  def range_to_add
    month = grant_date.month
    day = grant_date.mday
    year = Date.today.year
    last_grant_date = Time.local(year, month, day)

    if last_grant_date <= Date.today
      last_year = year - 1
      last_grant_date = Time.local(last_year, month, day)
    else
      two_years_ago = year - 2
      last_grant_date = Time.local(two_years_ago, month, day)
    end
    holidays.where(registration_date: last_grant_date..Date.tomorrow)
  end

  def total_delete_day
    range_to_delete.sum(:delete_day)
  end

  def total_add_day
    range_to_add.sum(:add_day)
  end

  def calculate_remaining_days
    a = total_delete_day
    b = total_add_day
    b - a
  end

  def delete_days_alert
    a = total_delete_day
    b = total_add_day

    if b >= 10 && a < 5
      "未消化"
    else
      "-"
    end
  end
end

app/models/holiday.rb
class Holiday < ApplicationRecord
  validates :reason, presence: true
  validates :add_day, :delete_day, exclusion: { in: [0]}
  validates :add_day, :delete_day, format: {with: /\A[0-9]+\z/, message: "は半角数字で入力して下さい"}

  belongs_to :user
  belongs_to :employee

  def add_or_delete
    if add_day.nil?
      "#{delete_day}日消化"
    elsif delete_day.nil?
      "#{add_day}日付与"
    else
      "#{add_day}日付与と#{delete_day}日消化"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true

  has_many :branches, dependent: :destroy
  has_many :holidays, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController

  before_action :set_branch, only: [:edit, :update, :destroy]
  
  def index
  end

  def new
    @branch = Branch.new
  end

  def create
    branch = Branch.new(branch_params)
    if branch.save
      redirect_to root_path, notice: :'支社の登録が完了しました'
    else
      @branch = Branch.new
      flash.now[:alert] = '登録できませんでした すべての項目を記入して下さい'
      render :new
    end
  end

  def edit
  end

  def update
    if @branch.update(branch_params)
      redirect_to root_path, notice: :'支社情報の更新が完了しました'
    else
      set_branch
      flash.now[:alert] = '更新できませんでした すべての項目を記入して下さい'
      render :edit
    end
  end

  def destroy
    if @branch.destroy
      redirect_to root_path, notice: :'支社を削除しました'
    else
      set_branch
      flash.now[:alert] = '支社の削除に失敗しました'
      render :edit
    end
  end
  
  private
  def branch_params
    params.require(:branch).permit(:name).merge(user_id: current_user.id)
  end

  def set_branch
    @branch = Branch.find(params[:id])
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  before_action :set_employee, only: [:edit, :update, :destroy]
  before_action :set_curent_user_branch, only: [:new, :create, :edit, :update]

  def index
    @branch = Branch.find(params[:branch_id])
    @employees = Employee.where(branch_id: params[:branch_id]).includes(:holidays)
  end
  
  def new
    @employee = Employee.new
  end

  def create
    employee = Employee.new(employee_params)
    if employee.save
      redirect_to branch_employees_path(employee_params[:branch_id]), notice: :'社員の登録が完了しました'
    else
      @employee = Employee.new
      flash.now[:alert] = '登録できませんでした すべての項目を記入して下さい'
      render :new
    end
  end

  def edit
  end

  def update
    branch_id = @employee.branch_id
    if @employee.update(employee_params)
      redirect_to branch_employees_path(branch_id), notice: :'社員情報の更新が完了しました'
    else
      set_curent_user_branch
      set_employee
      flash.now[:alert] = '更新できませんでした すべての項目を記入して下さい'
      render :edit
    end
  end

  def destroy
    branch_id = @employee.branch_id
    if @employee.destroy
      redirect_to branch_employees_path(branch_id), notice: :'社員を削除しました'
    else
      redirect_to root_path, alert: :'社員の削除に失敗しました'
    end
  end

  private
  def employee_params
    params.require(:employee).permit(:name, :employment_status, :hire_date, :branch_id)
  end

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def set_curent_user_branch
    @branch = Branch.where(user_id: current_user)
  end
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController

  before_action :set_branch, only: [:new]

  def index
    @holidays = Holiday.all.includes(:employee)
  end

  def new
    @holiday = Holiday.new
  end

  def create
    holiday = Holiday.new(holiday_params)
    if holiday.save
      redirect_to  branch_employees_path(params[:branch_id]), notice: :'有休登録が完了しました'
    else
      @holiday = Holiday.new
      set_branch
      flash.now[:alert] = '登録できませんでした すべての項目を記入して下さい'
      render :new
    end
  end

  def destroy
    holiday = Holiday.find(params[:id])
    if holiday.destroy
      redirect_to holidays_path, notice: :'有休情報を削除しました'
    else
      redirect_to holidays_path, alert: :'有休情報の削除に失敗しました'
    end
  end

  private
  def holiday_params
    params.require(:holiday).permit(:add_day, :delete_day, :reason, :registration_date,:employee_id).merge(user_id: current_user.id)
  end

  def set_branch
    @branch = Branch.find(params[:branch_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_blankmain.html.haml
.main
  =render 'branches/mainheader'
  .main__body
    .main__body__guide
      .main__body__guide__title
        「Backyard」の使い方
      .main__body__guide__text
        ①「支社登録」を実施。
        %br ②「社員登録」を実施。
        ③「メニュー」をクリックして支社を選択。
        %br ④支社に所属する社員の有休休暇管理表を確認。
        ⑤有給消化時は「有休登録」を実施。
        %br ⑥登録結果は、メニューの「付与または消化の履歴」から確認。

app/views/branches/_deletelog.html.haml
.main
  =render 'branches/mainheader'
  .logs__body
    - @holidays.each do |holiday|
      .log
        .log__top
          .left
            .left__text
              #{holiday.employee.branch.name}：
            .left__text
              = holiday.employee.name
          .created_at
            = holiday.created_at.strftime("%Y年%m月%d日")
        .log__low
          .reason 
            = holiday.reason
          .day
            #{holiday.delete_day}日消化

app/views/branches/_main.html.haml
.main
  =render 'branches/mainheader'
  .main__body
    %h2 #{@branch.name}の有給休暇管理表
    %p 社員データの編集は「名前」をクリック、削除は右端です。
    %table{class: "table table-bordered table-hover table-responsive"}
      %tr
        %th 名前
        %th 入社日
        %th{id: "short"}
          付与日
        %th
          勤続年数
        %th{id: "short"}
          付与日数
        %th{id: "short"}
          消化日数
        %th{id: "short"}
          残日数
        %th{id: "short", class: "bgc"}
          5日消化
        %th{id: "veryshort"}
        - @employees.each do |employee|
          %tr
            %th
              = link_to edit_employee_path(employee.id), class: "link" do
                = employee.name
            %th
              = employee.hire_date.strftime("%Y/%m/%d")
            %th{id: "short"}
              = employee.grant_date.strftime("%m/%d")
            %th
              = employee.year_of_service
            %th{id: "short"}
              = employee.total_add_day
            %th{id: "short"}
              = employee.total_delete_day
            %th{id: "short"}
              = employee.calculate_remaining_days
            %th{id: "short", class: "bgc"}
              = employee.delete_days_alert
            %th{id: "veryshort" }
              = link_to employee_path(employee.id), class: "link", method: :delete do
                削除

app/views/branches/_mainheader.html.haml
.main__header
  .nav
    .nav__logo
      = link_to root_path, class: "logo" do
        || Backyard ||
    .nav__ragistation
      = link_to "#", {class: "btn link", data:{action:'toggle', side:'left'}} do
        メニュー
    .nav__ragistation
      = link_to new_branch_path, class: "btn" do
        支社登録
    .nav__ragistation
      = link_to new_employee_path, class: "btn" do
        社員登録
  .right
    .right__name
      = current_user.name
    .right__signout
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'right__signout--link'

app/views/branches/_side.html.haml
.sidebar.left
  .sidebar__closed
    = link_to "#", {class: "btn", data:{action:'toggle', side:'left'}} do
      メニューを閉じる
  .sidebar__lists
    - current_user.branches.each do |branch|
      .list
        .list__top
          = link_to branch_employees_path(branch), class: "list__link" do
            .list__name
              = branch.name 
            .list__count
              %span 従業員：
              = branch.employees.count
              %span 名
        .list__bottom
          .bottom__btn
            = link_to edit_branch_path(branch.id), class: "list__link" do
              支社編集/削除
          .bottom__btn
            = link_to new_branch_holiday_path(branch), class: "list__link" do
              有休登録
  .sidebar__nav 
    .delete
      = link_to holidays_path, class: "delete__link" do
        付与または消化の履歴
    .links
      = link_to "https://drive.google.com/file/d/1NXmC35ZbmCOAqu7oGyCOc2LqipHDGDJj/view?usp=sharing", target: :_blank, class: "link" do
        有給休暇届
      = link_to "https://www.mhlw.go.jp/shingi/2004/04/s0428-7b2a.html", target: :_blank, class: "link" do
        関連サイト

app/views/branches/edit.html.haml
.branch
  .branch__body
    .branch__body__title
      #{@branch.name}の編集
    .branch__body__form
      = form_for @branch do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .btns
          = f.button "登録", type: :submit, class: "btn btn-default"
          = link_to branch_path(@branch), method: :delete do
            = f.button "支社削除", class: "btn btn-default"
        .alert
          .alert__text
            支社の削除を行う前に社員の所属先を変更して下さい。
            %br
            %br 支社削除を行った場合、以下のデータも削除されます。
            ●所属する社員のデータ
            %br ●削除した社員の有給休暇に関する履歴
            くれぐれもご注意下さい!!

app/views/branches/index.html.haml
.wrapper
  = render 'side'
  = render 'blankmain'

app/views/branches/new.html.haml
.branch
  .branch__body
    .branch__body__title
      新規支社登録
    .branch__body__form
      = form_for @branch do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .btns
          = f.button "登録", type: :submit, class:"btn btn-default"

app/views/employees/edit.html.haml
.employee
  .employee__body
    .employee__body__title
      #{@employee.name}さんの編集
    .employee__body__form
      = form_for @employee do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :employment_status
          .field-input
            = f.select :employment_status, [["フルタイム", "1"],["パートタイム", "2"]], include_blank: "選択して下さい"
        .field
          .field-label
            = f.label :hire_date
          .field-input
            != sprintf(f.date_select(:hire_date, prompt:"--", use_month_numbers:true, start_year:Time.now.year, end_year:1975, date_separator:'%s'),'年','月')+'日'
        .field
          .field-label
            = f.label :branch_id
          .field-input
            = f.collection_select :branch_id, @branch, :id, :name, include_blank: "選択して下さい"
        .btns
          = f.button "登録", type: :submit, class: "btn btn-default"

app/views/employees/index.html.haml
.wrapper
  =render 'branches/side'
  =render 'branches/main'

app/views/employees/new.html.haml
.employee
  .employee__body
    .employee__body__title
      新規社員登録
    .employee__body__form
      = form_for @employee do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :employment_status
          .field-input
            = f.select :employment_status, [["フルタイム", "1"],["パートタイム", "2"]], include_blank: "選択して下さい"
        .field
          .field-label
            = f.label :hire_date
          .field-input
            != sprintf(f.date_select(:hire_date, prompt:"--", use_month_numbers:true, start_year:Time.now.year, end_year:1975, date_separator:'%s'),'年','月')+'日'
        .field
          .field-label
            = f.label :branch_id
          .field-input
            = f.collection_select :branch_id, @branch, :id, :name, include_blank: "選択して下さい"
        .btns
          = f.button "登録", type: :submit, class: "btn btn-default"

app/views/holidays/_deletelog.html.haml
.main
  =render 'branches/mainheader'
  .logs__body
    - @holidays.each do |holiday|
      .log
        .log__top
          .log__top__left
            登録日：
            = holiday.registration_date.strftime("%Y年%m月%d日")
          .log__top__center
            #{holiday.employee.branch.name}：
            = holiday.employee.name
          .log__top__right
            = link_to holiday_path(holiday.id), class: "link", method: :delete do
              削除
        .log__low
          .reason 
            = holiday.reason
          .day
            = holiday.add_or_delete

app/views/holidays/index.html.haml
.wrapper
  = render 'branches/side'
  = render 'deletelog'

app/views/holidays/new.html.haml
.holiday
  .holiday__body
    .holiday__body__title
      #{@branch.name}社員の有給消化登録
    .holiday__body__form
      = form_for @holiday, url: branch_holidays_path do |f|
        .field
          .field-label
            = f.label :employee_id
          .field-input
            = f.collection_select :employee_id, @branch.employees, :id, :name, include_blank: "選択して下さい"
        .field
          .field-label
            = f.label :registration_date
          .field-input
            != sprintf(f.date_select(:registration_date, prompt:"--", use_month_numbers:true, start_year:Date.today.year, end_year:Date.today.year+1, date_separator:'%s'),'年','月')+'日'
        .field-days
          .field
            .field-label
              = f.label :delete_day
            .field-input
              = f.number_field :delete_day, max: "50", min: "1"
          .field
            .field-label
              = f.label :add_day
            .field-input
              = f.number_field :add_day, max: "50", min: "1"
        .field
          .field-label-reason
            = f.label :reason
          .field-input
            = f.text_field :reason, autofocus: true
        .btns
          = f.button "リセット", type: :reset, class: "btn btn-default"
          = f.button "登録", type: :submit, class: "btn btn-default"

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title Backyard
    %script{src: "//code.jquery.com/jquery-1.10.2.min.js" }
    %script{src: "//jillix.github.io/jQuery-sidebar/js/handlers.js" }
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notifications'
    = yield